#!/usr/bin/env python3
"""
texture_midi.py -- texture an EXISTING (untextured) MIDI object scene.

Runs INSIDE the MIDI-3D venv, with cwd=<MIDI-3D dir> and PYTHONPATH=<MIDI-3D dir>,
and INSIDE the VS Build Tools environment (vcvars64 + CUDA toolkit on PATH) so the
triton Poisson-blend and nvdiffrast CUDA kernels can compile on first use. The
wrapper that sets all of this up is generated by build_scene.py's step_texture();
this script is not meant to be launched directly.

It reuses an already-merged MIDI ``output.glb`` (so MIDI inference is not re-run),
splits the source RGB by the segmentation mask, and runs MV-Adapter + UV
projection per object via scripts.image_to_textured_scene.run_i2tex. Each object's
textured result is written as ``mesh_<i>_shaded.glb`` into --output, where ``i`` is
the object's index in the merged scene (object_<i>). build_scene.py reloads those
per-object files and re-anchors them with depth-align placement.

    python texture_midi.py --rgb room.png --seg segmentation.png \
        --scene midi_out/output.glb --label-map midi_out/object_label_map.json \
        --output midi_out/tex --seed 42
"""
import argparse
import json
import os
import sys

import numpy as np
import torch
import trimesh
from PIL import Image


def _numeric_suffix(name: str) -> int:
    tail = name.rsplit("_", 1)[-1]
    return int(tail) if tail.isdigit() else 0


def _ordered_scene(scene_path: str) -> trimesh.Scene:
    """Load the merged MIDI GLB, baking scene-graph transforms into vertices and
    re-adding geometry in numeric object order (object_0, object_1, ... rather
    than the lexicographic 'object_10' < 'object_2' that trimesh may load).

    run_i2tex zips ``scene.geometry.values()`` against the seg instances (which
    come sorted by label id), so the geometry must be in the same object order.
    """
    raw = trimesh.load(scene_path, process=False)
    if not isinstance(raw, trimesh.Scene):
        raw = trimesh.Scene(raw)

    ordered = trimesh.Scene()
    for gname, geom in sorted(raw.geometry.items(), key=lambda kv: _numeric_suffix(kv[0])):
        g = geom.copy()
        tf = raw.graph.get(gname)
        if tf is not None and isinstance(tf, tuple):
            g.apply_transform(tf[0])
        ordered.add_geometry(g, geom_name=gname)
    return ordered


def _filtered_seg(seg_path: str, label_list: list[int], out_path: str) -> str:
    """Write a copy of the segmentation mask keeping ONLY the labels that made it
    into the merged scene (label_list), zeroing everything else.

    split_seg_mask drops objects < 500 px before MIDI runs, but split_rgb_mask
    (used by run_i2tex) keeps every nonzero label. Without this filter a tiny
    dropped object would add an extra RGB crop and shift every mesh<->crop pair.
    Restricting the mask to label_list makes split_rgb_mask yield exactly one
    instance per object, in object order (label_list is already sorted).
    """
    seg = np.array(Image.open(seg_path).convert("L"))
    keep = set(int(l) for l in label_list)
    out = np.where(np.isin(seg, list(keep)), seg, 0).astype(np.uint8)
    Image.fromarray(out, mode="L").save(out_path)
    return out_path


def main():
    ap = argparse.ArgumentParser(description="Texture an existing MIDI scene")
    ap.add_argument("--rgb", required=True, help="source room image")
    ap.add_argument("--seg", required=True, help="instance segmentation mask")
    ap.add_argument("--scene", required=True,
                    help="existing untextured merged MIDI GLB (output.glb)")
    ap.add_argument("--label-map", default=None,
                    help="object_label_map.json (labels per object, in order)")
    ap.add_argument("--output", required=True, help="output dir for textured meshes")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    os.makedirs(args.output, exist_ok=True)

    # Imported here (not at top) so a missing MIDI/MV-Adapter dep produces a clear
    # message rather than an import error before argparse even runs.
    from scripts.image_to_textured_scene import (
        prepare_ig2mv_pipeline, prepare_texture_pipeline, run_i2tex)

    scene = _ordered_scene(args.scene)
    n_obj = len(scene.geometry)
    print(f"[texture_midi] {n_obj} objects from {args.scene}", flush=True)

    seg_path = args.seg
    if args.label_map and os.path.isfile(args.label_map):
        label_list = json.load(open(args.label_map))["labels"]
        if len(label_list) != n_obj:
            print(f"[texture_midi] WARNING: label_map has {len(label_list)} labels "
                  f"but scene has {n_obj} objects; mesh<->crop alignment may drift.",
                  flush=True)
        seg_path = _filtered_seg(args.seg, label_list,
                                 os.path.join(args.output, "seg_filtered.png"))
        print(f"[texture_midi] filtered seg to {len(set(label_list))} labels", flush=True)

    device, dtype = "cuda", torch.float16
    print("[texture_midi] preparing MV-Adapter (IG2MV) pipeline "
          "(first run downloads SDXL base + mv-adapter, ~7 GB)...", flush=True)
    ig2mv_pipe = prepare_ig2mv_pipeline(device, dtype)
    print("[texture_midi] preparing TexturePipeline (LaMa + RealESRGAN)...", flush=True)
    texture_pipe = prepare_texture_pipeline(device, dtype)

    print("[texture_midi] texturing objects (MV-Adapter -> UV projection)...\n"
          "  First object compiles triton/nvdiffrast CUDA kernels (slow); "
          "later objects reuse the cache. ~2-3 min/object on a 5090.", flush=True)
    textured = run_i2tex(ig2mv_pipe, texture_pipe, scene,
                         args.rgb, seg_path, args.seed, args.output)

    # run_i2tex already wrote mesh_<i>_shaded.glb per object (what build_scene
    # reloads); also export the combined scene for quick standalone inspection.
    combined = os.path.join(args.output, "textured_scene.glb")
    textured.export(combined)
    print(f"\n[texture_midi] done: {len(textured.geometry)} textured objects -> "
          f"{args.output} (per-object mesh_<i>_shaded.glb + textured_scene.glb)",
          flush=True)


if __name__ == "__main__":
    main()
